export const GET_SESSIONS_FROM_LOCAL_STORAGE = 'GET_SESSIONS_FROM_LOCAL_STORAGE';
export const ADD_SESSION = 'ADD_SESSION';
export const SET_SELECTED_SESSION = 'SET_SELECTED_SESSION';
export const GIVE_STORY_POINT = 'GIVE_STORY_POINT';
export const SET_NEW_DEVELOPER = 'SET_NEW_DEVELOPER';
export const SET_DEVELOPER = 'SET_DEVELOPER';
